In [26]:
import pandas as pd

In [27]:
df=pd.read_csv('../Deeplearning/Datasets/SMSSpamCollection.csv',sep="\t",names=['label','message'])

In [28]:
df

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [29]:
df['message'].loc[451]

'hanks lotsly!'

In [30]:
df.shape

(5572, 2)

In [31]:
import re 
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\svygralingam\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [32]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [33]:
corpus=[]
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z0-9]','',df['message'][i])
    review=review.lower()
    review=review.split()
    
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [34]:
corpus

['gountiljurongpointcrazyavailableonlyinbugisngreatworldlaebuffetcinetheregotamorewat',
 'oklarjokingwifuoni',
 'freeentryin2awklycomptowinfacupfinaltkts21stmay2005textfato87121toreceiveentryquestionstdtxtratetcsapply08452810075over18',
 'udunsaysoearlyhorucalreadythensay',
 'nahidontthinkhegoestousfhelivesaroundherethough',
 'freemsgheytheredarlingitsbeen3weeksnowandnowordbackidlikesomefunyouupforitstilltbokxxxstdchgstosend150torcv',
 'evenmybrotherisnotliketospeakwithmetheytreatmelikeaidspat',
 'asperyourrequestmellemelleoruminnaminungintenurunguvettamhasbeensetasyourcallertuneforallcallerspress9tocopyyourfriendscallertun',
 'winnerasavaluednetworkcustomeryouhavebeenselectedtoreceivea900prizerewardtoclaimcall09061701461claimcodekl341valid12hoursonli',
 'hadyourmobile11monthsormoreurentitledtoupdatetothelatestcolourmobileswithcameraforfreecallthemobileupdatecofreeon08002986030',
 'imgonnabehomesoonandidontwanttotalkaboutthisstuffanymoretonightkivecriedenoughtoday',
 'sixchancestowinca

In [36]:
#create bag of word
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,binary=True)
X=cv.fit_transform(corpus).toarray()

In [37]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
Y=pd.get_dummies(df['label'])
Y=Y.iloc[:,1].values

In [39]:
Y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [41]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,Y_train)

In [42]:
y_pred=spam_detect_model.predict(X_test)

In [43]:
from sklearn.metrics import classification_report,accuracy_score
print(accuracy_score(Y_test,y_pred))

0.8565022421524664


In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(ngram_range=(1,2),max_features=2500)
X=tf.fit_transform(corpus).toarray()

In [45]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [59]:
import gensim

In [60]:
from nltk.stem import WordNetLemmatizer
le=WordNetLemmatizer()

In [67]:
corpus=[]
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z0-9]','',df['message'][i])
    review=review.lower()
    review=review.split()
    
    review=[le.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [68]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [70]:
corpus

['gountiljurongpointcrazyavailableonlyinbugisngreatworldlaebuffetcinetheregotamorewat',
 'oklarjokingwifuoni',
 'freeentryin2awklycomptowinfacupfinaltkts21stmay2005textfato87121toreceiveentryquestionstdtxtratetcsapply08452810075over18s',
 'udunsaysoearlyhorucalreadythensay',
 'nahidontthinkhegoestousfhelivesaroundherethough',
 'freemsgheytheredarlingitsbeen3weeksnowandnowordbackidlikesomefunyouupforitstilltbokxxxstdchgstosend150torcv',
 'evenmybrotherisnotliketospeakwithmetheytreatmelikeaidspatent',
 'asperyourrequestmellemelleoruminnaminungintenurunguvettamhasbeensetasyourcallertuneforallcallerspress9tocopyyourfriendscallertune',
 'winnerasavaluednetworkcustomeryouhavebeenselectedtoreceivea900prizerewardtoclaimcall09061701461claimcodekl341valid12hoursonly',
 'hadyourmobile11monthsormoreurentitledtoupdatetothelatestcolourmobileswithcameraforfreecallthemobileupdatecofreeon08002986030',
 'imgonnabehomesoonandidontwanttotalkaboutthisstuffanymoretonightkivecriedenoughtoday',
 'sixchancesto

In [71]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [72]:
words

[[],
 [],
 ['freeentryin', 'stmay', 'textfato', 'over'],
 [],
 [],
 ['torcv'],
 [],
 [],
 ['claimcodekl', 'valid', 'hoursonly'],
 ['hadyourmobile'],
 [],
 ['to', 'poundstxtcsh', 'andsendto', 'cost', 'pday', 'days', 'info'],
 ['ldnw', 'rw'],
 [],
 [],
 [],
 [],
 ['ehurememberhow'],
 [],
 ['egenglandto', 'txt', 'poboxox', 'wq'],
 [],
 ['imgoingtotryfor'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['yeahhegotinat'],
 [],
 [],
 [],
 ['am'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['whoareyouseeing'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['congrats',
  'isyourscall',
  'starwars',
  'etcall',
  'freebx',
  'ip',
  'we',
  'pmdontmissout'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['bonusprizecall'],
 [],
 ['or', 'toclaimtxtdisto', 'ls', 'aj'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['ucancallmenow'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['yupnextstop'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['between', 'am', 'cashor', 'prize'],
 [],
 ['mk', 'ppw'],
 [],
 [],
 [],

In [74]:
model=gensim.models.Word2Vec(words,window=5,min_count=2)

In [75]:
model.wv.index_to_key

['ppm',
 'now',
 'valid',
 'ok',
 'hrsonly',
 'to',
 'privateyour',
 'landsroww',
 'orcall',
 'expires',
 'identifiercode',
 'pobox',
 'am',
 'only',
 'pmin',
 'cashora',
 'or',
 'just',
 'win',
 'thisisthe',
 'pm',
 'ptone',
 'cashor',
 'between',
 'mins',
 'on',
 'call',
 'nokiatone',
 'over',
 'xx',
 'ppmx',
 'optout',
 'ip',
 'we',
 'congrats',
 'wx',
 'days',
 'nowonly',
 'sk',
 'hlldn',
 'free',
 'croydoncr',
 'youhave',
 'thanx',
 'pmsgrcvdhgsuite',
 'wb',
 'okie',
 'shows',
 'freefor',
 'wq',
 'stweekno',
 'prize',
 'uz',
 'pleasecall',
 'info',
 'hadyourmobile',
 'st',
 'wc',
 'stockportsk',
 'pmmax',
 'box',
 'pmsg',
 'orno',
 'day',
 'xhcost',
 'age',
 'mobile',
 'wk',
 'ard',
 'pmcost',
 'wqnorm',
 'pwk',
 'hp',
 'sub',
 'pmsgcc',
 'nowhgsuite',
 'ls',
 'tncswwwldewcom',
 'hrs',
 'urgentcall',
 'nite',
 'oklor',
 'achance',
 'fl',
 'thyou',
 'yrs',
 'no',
 'get',
 'thurstyle',
 'thursmile',
 'thurpersonality',
 'rdurnature',
 'ndursmsand',
 'replyhl',
 'tcrw',
 'splcharacte

In [80]:
model.wv.similar_by_word('cash')

[('neighbourwewent', 0.2554183900356293),
 ('playerora', 0.22856630384922028),
 ('get', 0.2220013290643692),
 ('hb', 0.21754276752471924),
 ('monoorlionp', 0.2153664529323578),
 ('sendalogo', 0.2019815295934677),
 ('mobypubquizwina', 0.19660580158233643),
 ('prize', 0.19483549892902374),
 ('wq', 0.19368040561676025),
 ('youvewonyour', 0.1890394687652588)]

In [81]:
import numpy as np
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [82]:
from tqdm import tqdm

In [83]:
words[73]

[]

In [84]:
type(model.wv.index_to_key)

list

In [85]:
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|          | 0/5569 [00:00<?, ?it/s]C:\Users\svygralingam\AppData\Roaming\Python\Python39\site-packages\numpy\core\fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\svygralingam\AppData\Roaming\Python\Python39\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:00<00:00, 22540.29it/s]


In [86]:
x_new=np.array(X)

C:\Users\svygralingam\AppData\Local\Temp\5\ipykernel_32752\3307954269.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_new=np.array(X)


In [87]:
x_new

array([nan, nan,
       array([ 1.8485531e-03, -2.7571283e-03, -5.9358552e-03,  1.5198136e-03,
              -1.7195485e-03,  2.1626486e-03,  1.3652963e-03,  1.0347412e-03,
               1.3738713e-04, -1.6751330e-03, -5.6870980e-03, -1.0938161e-03,
              -3.2163195e-03,  6.1589880e-03, -5.3251055e-03,  1.8204466e-03,
               4.1519133e-03, -3.2358302e-03, -3.6356552e-03,  4.0223973e-04,
              -2.0592222e-03,  2.4421732e-03,  3.5565819e-03,  1.5361516e-03,
               5.1024472e-03, -2.1273547e-03, -5.8157830e-03,  4.2638369e-03,
               3.7099693e-03,  5.7460116e-03,  3.8405289e-03,  1.8187466e-03,
               3.3859897e-03,  1.4401220e-03, -6.1567794e-03,  2.1568097e-03,
               1.3965679e-03,  2.3456622e-04, -8.5348252e-04, -1.3288296e-03,
              -4.3573426e-03,  6.4719864e-04,  5.2176453e-03, -6.4882748e-03,
               7.9174689e-04, -2.1499624e-03, -1.5811018e-03, -6.1872723e-03,
               7.3665229e-04, -3.3300840e-03, -